spring:
  application:
    name: employee-cache-service
  profiles:
    active: localhost

  main:
    allow-bean-definition-overriding: true

info:
  component: Employee Cache Service


logging:
  level:
    root:
    com.project: DEBUG
server:
  port: 9791
---
spring:
  config:
    activate:
      on-profile: localhost
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

feign:
  employee-service:
    name: employee-service
    url: http://localhost:8762 #zuul edge server'in portu

eureka:
  client:
    service-url:
      default-zone: http://localhost:8791/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10